---
    version: '3'
    services:
    -- service stack --
      timestamp-command:
        image: sman6798/timestamp-command-service:latest
        restart: unless-stopped
        environment: 
          SERVER_PORT: 9000
          LOG_LEVEL: DEBUG
          KAFKA_BROKER: localhost:9092
          KAFKA_PUBLISH_TOPIC: timestamp.command
        depends_on: 
          - broker
    
      timestamp-consumer:
        image: sman6798/timestamp-consumer-service:latest
        restart: unless-stopped
        environment: 
          SERVER_PORT: 9000
          LOG_LEVEL: DEBUG
          KAFKA_BROKER: localhost:9092
          KAFKA_CONSUME_TOPIC: timestamp.command
        depends_on: 
          - broker
    
      timestamp-query:
        image: sman6798/timestamp-query-service:latest
        restart: unless-stopped
        environment: 
          SERVER_PORT: 9000
          DB_URL: localhost:9092
          # todo migrate to secrets
          url: "jdbc:postgresql://localhost:5432/postgres"
          username: postgres
          password: postgres
        depends_on: 
          - postgres
    