---
version: '3'
services:
# -- service stack --
  timestamp-command:
    image: sman6798/timestamp-command-service:latest
    restart: always
    environment: 
      SERVER_PORT: 9000
      LOG_LEVEL: DEBUG
      KAFKA_BROKER: localhost:9092
      KAFKA_PUBLISH_TOPIC: timestamp.command
    depends_on: 
      - broker

  timestamp-consumer:
    image: sman6798/timestamp-consumer-service:latest
    restart: always
    environment: 
      SERVER_PORT: 9000
      LOG_LEVEL: DEBUG
      KAFKA_BROKER: localhost:9092
      KAFKA_CONSUME_TOPIC: timestamp.command
    depends_on: 
      - broker

  timestamp-query:
    image: sman6798/timestamp-query-service:latest
    restart: always
    environment: 
      SERVER_PORT: 9000
      DB_URL: localhost:9092
      # todo migrate to secrets
      url: "jdbc:postgresql://localhost:5432/postgres"
      username: postgres
      password: postgres
    depends_on: 
      - postgres

# -- postgres stack (for dev)
  postgres:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    
  postgres-admin:
    image: adminer
    ports:
      - 9090:8080
    depends_on: 
      - postgres
  
# -- confluent kafka stack --  
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:5.5.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101